Config = {}
Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' -- Use qb-target interactions (don't change this, go to your server.cfg and add `setr UseTarget true` to use this and just that from true to false or the other way around)
Config.FirearmsLicenseCheck = false -- Whether a arms dealer checks for a firearms license
Config.SellCasinoChips = {
    coords = vector4(950.37, 34.72, 71.87, 33.82),
    radius = 1.5,
    ped = 's_m_y_casino_01'
}
Config.Products = {
    ["tokomakanan"] = {
        [1] = {
            name = "barr-bubblegum",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },  
        [2] = {
            name = "barr-cherryade",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },  
        [3] = {
            name = "barr-cola",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },  
        [4] = {
            name = "barr-creamsoda",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },  
        [5] = {
            name = "barr-lemonade",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },  
        [6] = {
            name = "cadbury-hotchocolate",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },  
        [7] = {
            name = "calypso-lemonage",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },  
        [8] = {
            name = "calypso-oceanblue",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },  
        [9] = {
            name = "calypso-pineapplepeach",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },  
        [10] = {
            name = "calypso-pradisepunch",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },  
        [11] = {
            name = "calypso-strawberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },  
        [12] = {
            name = "calypso-triplemelon",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },  
        [13] = {
            name = "coke-cherry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 13,
        },  
        [14] = {
            name = "coke-cinnamon",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 14,
        },  
        [15] = {
            name = "coke-coffee",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
        },  
        [16] = {
            name = "coke-diet",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 16,
        },  
        [17] = {
            name = "coke-mango",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 17,
        },  
        [18] = {
            name = "coke-peach",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 18,
        },  
        [19] = {
            name = "drpepper-cherry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 19,
        },  
        [20] = {
            name = "drpepper-cola",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 20,
        },  
        [21] = {
            name = "fanta-grape",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 21,
        },  
        [21] = {
            name = "fanta-grape",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 21,
        },  
        [22] = {
            name = "fanta-orange",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 22,
        },  
        [23] = {
            name = "fanta-peach",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 23,
        },  
        [24] = {
            name = "fanta-pineapple",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 24,
        },  
        [25] = {
            name = "fanta-strawberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 25,
        },  
        [26] = {
            name = "ka-blackgrape",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 26,
        },  
        [27] = {
            name = "ka-fruitpunch",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 27,
        },  
        [28] = {
            name = "ka-pineapple",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 28,
        },  
        [29] = {
            name = "ka-strawberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 29,
        },  
        [30] = {
            name = "ka-tropicalkrush",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 30,
        },  
        [31] = {
            name = "kenco-americano",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 31,
        },  
        [32] = {
            name = "kenco-cappaccino",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 32,
        },  
        [33] = {
            name = "kenco-latte",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 33,
        },  
        [34] = {
            name = "lucozade-apple",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 34,
        },  
        [35] = {
            name = "lucozade-cherry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 35,
        },  
        [36] = {
            name = "lucozade-mango",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 36,
        },  
        [37] = {
            name = "lucozade-orange",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 37,
        },  
        [38] = {
            name = "marinda-orange",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 38,
        },  
        [39] = {
            name = "marinda-strawberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 39,
        },  
        [40] = {
            name = "oasis-blackcurrentapple",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 40,
        },  
        [41] = {
            name = "oasis-citruspunch",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 41,
        },  
        [42] = {
            name = "oasis-summerfruits",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 42,
        },  
        [43] = {
            name = "prime-blueraspberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 43,
        },  
        [44] = {
            name = "prime-grape",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 44,
        },  
        [45] = {
            name = "prime-icepop",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 45,
        },  
        [46] = {
            name = "prime-lemonlime",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 46,
        },  
        [47] = {
            name = "prime-metamoon",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 47,
        },  
        [48] = {
            name = "prime-orange",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 48,
        },  
        [49] = {
            name = "ribena-pineapple",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 49,
        },  
        [50] = {
            name = "ribena-raspberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 50,
        },  
        [51] = {
            name = "ribena-strawberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 51,
        },  
        [52] = {
            name = "rubicon-cherryraspberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 52,
        },  
        [53] = {
            name = "rubicon-orangemango",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 53,
        },  
        [54] = {
            name = "rubicon-strawberrykiwi",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 54,
        },  
        [55] = {
            name = "vimto-orange",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 55,
        },  
        [56] = {
            name = "vimto-orangepineapple",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 56,
        },  
        [57] = {
            name = "vimto-original",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 57,
        },  
        [58] = {
            name = "vimto-strawberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 58,
        },  
        [59] = {
            name = "yazoo-banana",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 59,
        },  
        [60] = {
            name = "yazoo-chocolate",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 60,
        },  
        [61] = {
            name = "yazoo-strawberry",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 61,
        },  
        [62] = {
            name = "yazoo-vanilla",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 62,
        },  
        [63] = {
            name = "yorkshire-tea",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 63,
        },  

        --- Makanan
        [64] = {
            name = "marshy-aero",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 64,
        }, 
        [65] = {
            name = "marshy-beanz",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 65,
        }, 
        [66] = {
            name = "marshy-bourbon",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 66,
        }, 
        [67] = {
            name = "marshy-bubbaloo",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 67,
        }, 
        [68] = {
            name = "marshy-bueno",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 68,
        }, 
---------------------------------
        [69] = {
            name = "marshy-chrunchie",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 69,
        }, 
        [70] = {
            name = "marshy-corner.bcf",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 70,
        }, 
        [71] = {
            name = "marshy-corner.s",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 71,
        }, 
        [72] = {
            name = "marshy-corner.vcb",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 72,
        }, 
        [73] = {
            name = "marshy-creame-egg",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 73,
        }, 
        [74] = {
            name = "marshy-crumpets",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 74,
        }, 
        [75] = {
            name = "marshy-custard-cream",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 75,
        }, 
        [76] = {
            name = "marshy-dairymilk",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 76,
        }, 
        [77] = {
            name = "marshy-dibdabs",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 77,
        }, 
        [78] = {
            name = "marshy-digestive",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 78,
        }, 
        [79] = {
            name = "marshy-dorito.classic",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 79,
        }, 
        [80] = {
            name = "marshy-dorito.coolranch",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 80,
        }, 
        [81] = {
            name = "marshy-dorito.flaming",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 81,
        }, 
        [82] = {
            name = "marshy-dorito.heatwave",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 82,
        }, 
        [83] = {
            name = "marshy-dunkers",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 83,
        }, 
        [84] = {
            name = "marshy-flake",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 84,
        }, 
        [85] = {
            name = "marshy-frazzles",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 85,
        }, 
        [86] = {
            name = "marshy-greggs.d",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 86,
        }, 
        [87] = {
            name = "marshy-hobnobs",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 87,
        }, 
        [88] = {
            name = "marshy-greggs.sr",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 88,
        }, 
        [89] = {
            name = "marshy-hula-hoops",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 89,
        }, 
        [90] = {
            name = "marshy-jammy-dodger",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 90,
        }, 
    },
    ["tokosemua"] = {
        [1] = {
            name = "backpack1",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "backpack2",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "briefcase",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "paramedicbag",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "boombox",
            price = 1146,
            amount = 2,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "skateboard",
            price = 1146,
            amount = 2,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "caraudiosystem",
            price = 1146,
            amount = 2,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "vape",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "vapejuice",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "emptyvape",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "uwupurpleplush",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "uwugreenplush",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "uwublueplush",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "uwubrownplush",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "uwubrownplush",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
        },
        [16] = {
            name = "uwuredplush",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 16,
        },
        [17] = {
            name = "uwugreenrareplush",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 17,
        },
        [18] = {
            name = "uwupinkrareplush",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 18,
        },
        [19] = {
            name = "gardengloves",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 19,
        },
        [20] = {
            name = "shroombaggy",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 20,
        },
        [21] = {
            name = "shroombag",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 21,
        },
        [22] = {
            name = "shroom",
            price = 1146,
            amount = 50,
            info = {},
            type = "item",
            slot = 22,
        },
        [23] = {
            name = "screwdriver",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 23,
        },
        [24] = {
            name = "wd40",
            price = 40,
            amount = 50,
            info = {},
            type = "item",
            slot = 24,
        },
        [25] = {
            name = "blowtorch",
            price = 1000,
            amount = 50,
            info = {},
            type = "item",
            slot = 25,
        },	
        [26] = {
            name = "weapon_battleaxe",
            price = 750,
            amount = 50,
            info = {},
            type = "item",
            slot = 26,
        },
    },
    ["gacha"] = {
      [1] = {
        name = "randombox",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 1,
      },  
      [2] = {
        name = "randomcase",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 2,
      },  
      [3] = {
        name = "randombag",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 3,
      },  
      [4] = {
        name = "randomammo",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 4,
      },  
      [5] = {
        name = "randommedkit",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 5,
      },   
      [6] = {
        name = "randomgun",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 6,
      },   
      [7] = {
        name = "mystery_smallbox",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 7,
      },   
      [8] = {
        name = "mystery_mediumbox",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 8,
      },   
      [9] = {
        name = "mystery_bigbox",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 9,
      },   
      [10] = {
        name = "mystery_expensivebox",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 9,
      },   
    },
    ["tani"] = {
      [1] = {
        name = "garden_pitcher",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 1,
      },  
      [2] = {
        name = "garden_shovel",
        price = 10,
        amount = 50,
        info = {},
        type = "item",
        slot = 2,
      }  
    },
    ["normal"] = {
        [1] = {
            name = "tosti",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "water_bottle",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "kurkakola",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "twerks_candy",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "snikkel_candy",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "sandwich",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [6] = {
            name = "sandwich",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        
    },

    ["liquor"] = {
        [1] = {
            name = "beer",
            price = 7,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "whiskey",
            price = 10,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "vodka",
            price = 12,
            amount = 50,
            info = {},
            type = "item",
            slot = 3,
        },
    },
    ["hardware"] = {
        [1] = {
            name = "lockpick",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_wrench",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hammer",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "repairkit",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 4,
            requiredJob = { "mechanic", "police" }
        },
        [5] = {
            name = "screwdriverset",
            price = 350,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
        },
        [6] = {
            name = "phone",
            price = 850,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
        },
        [7] = {
            name = "radio",
            price = 250,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
        },
        [8] = {
            name = "binoculars",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
        },
        [9] = {
            name = "firework1",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
        },
        [10] = {
            name = "firework2",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 10,
        },
        [11] = {
            name = "firework3",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 11,
        },
        [12] = {
            name = "firework4",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 12,
        },
        [13] = {
            name = "fitbit",
            price = 400,
            amount = 150,
            info = {},
            type = "item",
            slot = 13,
        },
        [14] = {
            name = "cleaningkit",
            price = 150,
            amount = 150,
            info = {},
            type = "item",
            slot = 14,
        },
        [15] = {
            name = "advancedrepairkit",
            price = 500,
            amount = 50,
            info = {},
            type = "item",
            slot = 15,
            requiredJob = { "mechanic" }
        },
    },
    ["weedshop"] = {
        [1] = {
            name = "joint",
            price = 10,
            amount = 1000,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_poolcue",
            price = 100,
            amount = 1000,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weed_nutrition",
            price = 20,
            amount = 1000,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "empty_weed_bag",
            price = 2,
            amount = 1000,
            info = {},
            type = "item",
            slot = 4,
        },
        [5] = {
            name = "rolling_paper",
            price = 2,
            amount = 1000,
            info = {},
            type = "item",
            slot = 5,
        },
    },
    ["gearshop"] = {
        [1] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "jerry_can",
            price = 200,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
    },
    ["leisureshop"] = {
        [1] = {
            name = "parachute",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "binoculars",
            price = 50,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "diving_gear",
            price = 2500,
            amount = 10,
            info = {},
            type = "item",
            slot = 3,
        },
        [4] = {
            name = "diving_fill",
            price = 500,
            amount = 10,
            info = {},
            type = "item",
            slot = 4,
        },
        -- [4] = {
        --     name = "smoketrailred",
        --     price = 250,
        --     amount = 50,
        --     info = {},
        --     type = "item",
        --     slot = 4,
        -- },
    },
    ["weapons"] = {
        [1] = {
            name = "weapon_knife",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "weapon_bat",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 2,
        },
        [3] = {
            name = "weapon_hatchet",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 3,
            requiredJob = { "mechanic", "police" }
        },
        [4] = {
            name = "weapon_pistol",
            price = 2500,
            amount = 5,
            info = {},
            type = "item",
            slot = 4,
            requiresLicense = true
        },
        [5] = {
            name = "weapon_snspistol",
            price = 1500,
            amount = 5,
            info = {},
            type = "item",
            slot = 5,
            requiresLicense = true
        },
        [6] = {
            name = "weapon_vintagepistol",
            price = 4000,
            amount = 5,
            info = {},
            type = "item",
            slot = 6,
            requiresLicense = true
        },
        [7] = {
            name = "weapon_ak47",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 7,
            requiresLicense = true
        },
        [8] = {
            name = "weapon_m70",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 8,
            requiresLicense = true
        },
        [9] = {
            name = "weapon_de",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 9,
            requiresLicense = true
        },
        [10] = {
            name = "weapon_fnx45",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 10,
            requiresLicense = true
        },
        [11] = {
            name = "weapon_glock17",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 11,
            requiresLicense = true
        },
        [12] = {
            name = "weapon_m4",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 12,
            requiresLicense = true
        },
        [13] = {
            name = "weapon_m9",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 13,
            requiresLicense = true
        },
        [14] = {
            name = "weapon_m1911",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 14,
            requiresLicense = true
        },
        [15] = {
            name = "weapon_uzi",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 15,
            requiresLicense = true
        },
        [16] = {
            name = "weapon_mac10",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 16,
            requiresLicense = true
        },
        [17] = {
            name = "weapon_mossberg",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 17,
            requiresLicense = true
        },
        [18] = {
            name = "weapon_remington",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 18,
            requiresLicense = true
        },
        [19] = {
            name = "weapon_scarh",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 19,
            requiresLicense = true
        },
        [20] = {
            name = "weapon_shiv",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 20,
            requiresLicense = true
        },
        [21] = {
            name = "weapon_katana",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 21,
            requiresLicense = true
        },
        [22] = {
            name = "weapon_sledgehammer",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 22,
            requiresLicense = true
        },
        [23] = {
            name = "weapon_ar15",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 23,
            requiresLicense = true
        },
        [24] = {
            name = "weapon_mk14",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 24,
            requiresLicense = true
        },
        [25] = {
            name = "weapon_huntingrifle",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 25,
            requiresLicense = true
        },
        [26] = {
            name = "weapon_mp9",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 26,
            requiresLicense = true
        },
        [27] = {
            name = "weapon_m110",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 27,
            requiresLicense = true
        },
        [28] = {
            name = "weapon_hk416",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 28,
            requiresLicense = true
        },
        [29] = {
            name = "weapon_ak74",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 29,
            requiresLicense = true
        },
        [30] = {
            name = "weapon_aks74",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 30,
            requiresLicense = true
        },
        [31] = {
            name = "weapon_glock22",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 31,
            requiresLicense = true
        },
        [32] = {
            name = "weapon_glock18c",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 32,
            requiresLicense = true
        },
        [33] = {
            name = "weapon_mp5",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 33,
            requiresLicense = true
        },
        [34] = {
            name = "weapon_karambit",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 34,
            requiresLicense = true
        },
        [35] = {
            name = "weapon_colbaton",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 35,
            requiresLicense = true
        },
        [36] = {
            name = "pistol_ammo",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 36,
            requiresLicense = true
        },
        [37] = {
            name = "rifle_ammo",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 37,
            requiresLicense = true
        },
        [38] = {
            name = "snp_ammo",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 38,
            requiresLicense = true
        },
        [39] = {
            name = "smg_ammo",
            price = 250,
            amount = 250,
            info = {},
            type = "item",
            slot = 39,
            requiresLicense = true
        },
    },
    ["casino"] = {
        [1] = {
            name = 'casinochips',
            price = 1,
            amount = 999999,
            info = {},
            type = 'item',
            slot = 1,
        }
    },
}
Config.Locations = {
    -- TOKO Makanan
    ["tokomakanan"] = {
        ["label"] = "Toko Makanan & Minuman",
        ["coords"] = vector4(-1286.4, -1386.02, 4.45, 201.22),
        ["ped"] = 's_m_y_chef_01',
        ["scenario"] = "WORLD_HUMAN_AA_COFFEE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cubes",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["tokomakanan"],
        ["showblip"] = true,
        ["blipsprite"] = 605,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 46
    },
    -- TOKO SEMUA
    ["tokosemua"] = {
        ["label"] = "Toko Serba Ada",
        ["coords"] = vector4(-1341.99, -1234.48, 5.94, 110.7),
        ["ped"] = 'a_m_y_bevhills_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cubes",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["tokosemua"],
        ["showblip"] = true,
        ["blipsprite"] = 605,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 46
    },

    -- gacha
    ["gacha"] = {
        ["label"] = "Toko Gacha",
        ["coords"] = vector4(-1119.31, -1652.1, 4.36, 127.26),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cubes",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["gacha"],
        ["showblip"] = true,
        ["blipsprite"] = 457,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 46
    },


    -- TANI
    ["Tani"] = {
        ["label"] = "Toko Tani",
        ["coords"] = vector4(2310.6, 4884.84, 41.81, 47.2),
        ["ped"] = 'a_m_m_hillbilly_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cubes",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["tani"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 5
    },


    -- 24/7 Locations
    ["247supermarket"] = {
        ["label"] = "Warung 24 Jam",
        ["coords"] = vector4(24.47, -1346.62, 29.5, 271.66),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket2"] = {
        ["label"] = "Warung 24 Jam",
        ["coords"] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket3"] = {
        ["label"] = "Warung 24 Jam",
        ["coords"] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket4"] = {
        ["label"] = "Warung 24 Jam",
        ["coords"] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket5"] = {
        ["label"] = "Warung 24 Jam",
        ["coords"] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket6"] = {
        ["label"] = "Warung 24 Jam",
        ["coords"] = vector4(549.13, 2670.85, 42.16, 99.39),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket7"] = {
        ["label"] = "Warung 24 Jam",
        ["coords"] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket8"] = {
        ["label"] = "Warung 24 Jam",
        ["coords"] = vector4(2556.66, 380.84, 108.62, 356.67),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["247supermarket9"] = {
        ["label"] = "Warung 24 Jam",
        ["coords"] = vector4(372.66, 326.98, 103.57, 253.73),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    -- LTD Gasoline Locations
    ["ltdgasoline"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["ltdgasoline2"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-706.06, -913.97, 19.22, 88.04),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["ltdgasoline3"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["ltdgasoline4"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1164.71, -322.94, 69.21, 101.72),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["ltdgasoline5"] = {
        ["label"] = "LTD Gasoline",
        ["coords"] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["normal"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    -- Rob's Liquor Locations
    ["robsliquor"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["robsliquor2"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["robsliquor3"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["robsliquor4"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    ["robsliquor5"] = {
        ["label"] = "Rob's Liqour",
        ["coords"] = vector4(1134.2, -982.91, 46.42, 277.24),
        ["ped"] = 'mp_m_shopkeep_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    -- Hardware Store Locations
    ["hardware"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(45.68, -1749.04, 29.61, 53.13),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    ["hardware2"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Open Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    ["hardware3"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    -- Ammunation Locations
    ["ammunation"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(-661.96, -933.53, 21.83, 177.05),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation2"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(809.68, -2159.13, 29.62, 1.43),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation3"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation4"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation5"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(253.63, -51.02, 69.94, 72.91),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation6"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(23.0, -1105.67, 29.8, 162.91),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation7"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(2567.48, 292.59, 108.73, 349.68),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation8"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation9"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(841.92, -1035.32, 28.19, 1.56),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation10"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },
    ["ammunation11"] = {
        ["label"] = "Toko Senjata",
        ["type"] = "weapon",
        ["coords"] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ["ped"] = 's_m_y_ammucity_01',
        ["scenario"] = "WORLD_HUMAN_COP_IDLES",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-gun",
        ["targetLabel"] = "Open Ammunation",
        ["products"] = Config.Products["weapons"],
        ["showblip"] = true,
        ["blipsprite"] = 110,
        ["blipscale"] = 0.6,
        ["blipcolor"] = 0
    },

    -- Casino Locations
    ["casino"] = {
        ["label"] = "Diamond Casino",
        ["coords"] = vector4(949.29, 32.13, 71.95, 79.54),
        ["ped"] = 'csb_tomcasino',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-coins",
        ["targetLabel"] = "Buy Chips",
        ["products"] = Config.Products["casino"],
        ["showblip"] = true,
        ["blipsprite"] = 617,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    ["casinobar"] = {
        ["label"] = "Casino Bar",
        ["coords"] = vector4(937.45, 27.22, 71.83, 61.21),
        ["ped"] = 'a_m_y_smartcaspat_01',
        ["scenario"] = "WORLD_HUMAN_VALET",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wine-bottle",
        ["targetLabel"] = "Open Casino Bar",
        ["products"] = Config.Products["liquor"],
        ["showblip"] = false,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    -- Weedshop Locations
    ["weedshop"] = {
        ["label"] = "Smoke On The Water",
        ["coords"] = vector4(-1168.26, -1573.2, 4.66, 105.24),
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cannabis",
        ["targetLabel"] = "Open Weed Shop",
        ["products"] = Config.Products["weedshop"],
        ["showblip"] = true,
        ["blipsprite"] = 140,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    -- Sea Word Locations
    ["seaword"] = {
        ["label"] = "Sea Word",
        ["coords"] = vector4(-1687.03, -1072.18, 13.15, 52.93),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_IMPATIENT",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-fish",
        ["targetLabel"] = "Sea Word",
        ["products"] = Config.Products["gearshop"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },

    -- Leisure Shop Locations
    ["leisureshop"] = {
        ["label"] = "Leisure Shop",
        ["coords"] = vector4(-1505.91, 1511.95, 115.29, 257.13),
        ["ped"] = 'a_m_y_beach_01',
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-leaf",
        ["targetLabel"] = "Open Leisure Shop",
        ["products"] = Config.Products["leisureshop"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipscale"] = 0.8,
        ["blipcolor"] = 0
    },
}
